# Generated by Django 5.1 on 2024-09-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name="Organisation",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("org_name", models.CharField(max_length=200)),
			],
		),
		migrations.CreateModel(
			name="Post",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("post_text", models.TextField(max_length=2000)),
				("pub_date", models.DateTimeField(verbose_name="date published")),
				("votes", models.IntegerField(default=0)),
			],
		),
		migrations.CreateModel(
			name="Comment",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("comment_text", models.TextField(max_length=2000)),
				("pub_date", models.DateTimeField(verbose_name="date published")),
				("votes", models.IntegerField(default=0)),
				(
					"post",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to="app.post"
					),
				),
			],
		),
		migrations.CreateModel(
			name="User",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("username", models.CharField(max_length=200)),
				(
					"organisation",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to="app.organisation",
					),
				),
			],
		),
		migrations.AddField(
			model_name="post",
			name="user",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to="app.user"
			),
		),
	]
