# Generated by Django 5.1 on 2024-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0001_initial"),
	]

	operations = [
		migrations.AddField(
			model_name="post",
			name="post_title",
			field=models.CharField(default="Untitled Post", max_length=200),
		),
		migrations.AlterField(
			model_name="comment",
			name="pub_date",
			field=models.DateTimeField(auto_now_add=True),
		),
		migrations.AlterField(
			model_name="post",
			name="pub_date",
			field=models.DateTimeField(auto_now_add=True),
		),
	]
