# Generated by Django 5.1 on 2024-09-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0002_post_post_title_alter_comment_pub_date_and_more"),
	]

	operations = [
		migrations.RenameField(
			model_name="comment",
			old_name="post",
			new_name="post_id",
		),
		migrations.RenameField(
			model_name="post",
			old_name="user",
			new_name="user_id",
		),
		migrations.RenameField(
			model_name="user",
			old_name="organisation",
			new_name="organisation_id",
		),
		migrations.AddField(
			model_name="post",
			name="organisation_id",
			field=models.ForeignKey(
				default=1,
				on_delete=django.db.models.deletion.CASCADE,
				to="app.organisation",
			),
			preserve_default=False,
		),
	]
