# Generated by Django 5.1 on 2024-09-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0003_rename_post_comment_post_id_rename_user_post_user_id_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="comment",
			name="user_id",
			field=models.ForeignKey(
				default=1, on_delete=django.db.models.deletion.CASCADE, to="app.user"
			),
			preserve_default=False,
		),
	]
