# Generated by Django 5.1 on 2024-09-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0005_alter_user_options_alter_user_managers_and_more"),
	]

	operations = [
		migrations.AlterField(
			model_name="user",
			name="organisation_id",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to="app.organisation",
			),
		),
	]
