# Generated by Django 5.1 on 2024-10-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0006_alter_user_organisation_id"),
	]

	operations = [
		migrations.AddField(
			model_name="organisation",
			name="seats_remaining",
			field=models.IntegerField(default=10),
			preserve_default=False,
		),
		migrations.AddField(
			model_name="user",
			name="is_org_admin",
			field=models.BooleanField(default=False),
		),
		migrations.AlterField(
			model_name="user",
			name="is_active",
			field=models.BooleanField(default=True),
		),
	]
