# Generated by Django 5.1 on 2024-10-09 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0007_organisation_seats_remaining_user_is_org_admin_and_more"),
	]

	operations = [
		migrations.AddField(
			model_name="comment",
			name="organisation",
			field=models.ForeignKey(
				default="firmsnap",
				on_delete=django.db.models.deletion.CASCADE,
				to="app.organisation",
			),
			preserve_default=False,
		),
	]
