# Generated by Django 5.1 on 2024-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("app", "0008_comment_organisation_id"),
	]

	operations = [
		migrations.AddField(
			model_name="organisation",
			name="seats_paid_for",
			field=models.IntegerField(default=13),
			preserve_default=False,
		),
	]
