# Generated by Django 5.1 on 2024-10-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		("app", "0008_comment_organisation"),
	]

	operations = [
		migrations.RenameField(
			model_name="comment",
			old_name="organisation",
			new_name="organisation_id",
		),
	]
